name = "mon-blog"
type = "webpack"
account_id = "79acc6c68003ac9ef4666a7a5ccf8761"
workers_dev = false
route = "mon-blog.vence.tech/*"
zone_id = "e1dff329fb167a506d1b814ceea7435d"

[site]
bucket = "./public"
entry-point = "workers-site"
